\set ON_ERROR_STOP on

-- This file is run only inside a disposable local PostgreSQL database created by
-- run-database-integration.mjs. It never connects to Supabase or production.
create schema auth;
create table auth.users (id uuid primary key);
create function auth.jwt() returns jsonb
language sql stable
as $$ select coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb, '{}'::jsonb) $$;
create function auth.uid() returns uuid
language sql stable
as $$ select nullif(auth.jwt() ->> 'sub', '')::uuid $$;
grant usage on schema auth to anon, authenticated, service_role;
grant execute on function auth.jwt(), auth.uid() to anon, authenticated, service_role;

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null check (price >= 0),
  image text
);
alter table public.products enable row level security;
revoke all on public.products from public, anon, authenticated;
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
create policy products_public_select on public.products for select to anon, authenticated using (true);
create policy products_admin_write on public.products for all to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

insert into public.products (id, name, category, price, image) values
  (1, 'Test box', 'boxes', 100, null),
  (2, 'Race product', 'boxes', 20, null),
  (3, 'Uninitialized product', 'boards', 5, null);

\ir ../database/orders-migration.sql
\ir ../database/order-security-migration.sql

-- Simulates a delivered order that existed before the accounting migration.
insert into public.orders (
  id, created_at, first_name, last_name, phone, governorate, city, address,
  building, floor, apartment, items, subtotal, shipping, total, status
) values (
  '00000000-0000-4000-8000-000000000001', '2024-03-10 10:00:00+02',
  'Old', 'Customer', '01012345678', 'القاهرة', 'القاهرة', 'Test address',
  '1', '1', '1', '[{"product_id":1,"name":"Test box","unit_price":100,"quantity":1}]',
  100, 65, 165, 'delivered'
);

\ir ../database/admin-inventory-accounts-migration.sql
\ir ../database/delivered-orders-accounting-migration.sql
\ir ../database/order-inventory-availability-migration.sql
\ir ../database/public-product-availability-migration.sql

insert into auth.users (id) values ('10000000-0000-4000-8000-000000000001');
select set_config('request.jwt.claims', '{"sub":"10000000-0000-4000-8000-000000000001","app_metadata":{"role":"admin"}}', false);
select public.record_inventory_movement(1, 'opening', 5, 1, 'test opening');
select public.record_inventory_movement(2, 'opening', 1, 0, 'one unit for race test');

-- A pending order created before the new reservation migration must be reserved
-- by that migration before new checkouts are accepted.
insert into public.orders (
  id, created_at, first_name, last_name, phone, governorate, city, address,
  building, floor, apartment, items, subtotal, shipping, total, status
) values (
  '00000000-0000-4000-8000-000000000002', '2025-03-10 10:00:00+02',
  'Pending', 'Customer', '01012345678', 'القاهرة', 'القاهرة', 'Test address',
  '1', '1', '1', '[{"product_id":1,"name":"Test box","unit_price":100,"quantity":1}]',
  100, 65, 165, 'pending'
);

\ir ../database/order-reservation-returns-migration.sql

-- Create one return under the previous accounting behavior. The accounting
-- migration must reclassify it from expense to sales return without changing it.
select public.record_order_return(
  '70000000-0000-4000-8000-000000000002',
  '00000000-0000-4000-8000-000000000001',
  '[{"product_id":1,"quantity":1,"disposition":"damaged"}]'::jsonb,
  'other', 'legacy return migration test'
);

\ir ../database/sales-returns-accounting-migration.sql
\ir ../database/product-cost-profit-migration.sql

update public.product_costs set unit_cost = 9 where product_id = 1;
update public.product_costs set unit_cost = 10 where product_id = 2;
update public.product_costs set unit_cost = 2 where product_id = 3;

do $$
declare
  v_entry record;
  v_order jsonb;
  v_replay jsonb;
  v_order_id uuid;
  v_return_id uuid;
  v_return_replay uuid;
  v_count integer;
begin
  select * into v_entry from public.account_entries
  where order_id = '00000000-0000-4000-8000-000000000001';
  if not found or v_entry.amount <> 100 or v_entry.entry_date <> date '2024-03-10' then
    raise exception 'FAIL: historical delivered order was not backfilled with its original Cairo date and product subtotal';
  end if;

  if has_table_privilege('anon', 'public.orders', 'insert')
    or has_table_privilege('authenticated', 'public.orders', 'insert') then
    raise exception 'FAIL: public or authenticated users can insert orders directly';
  end if;
  if has_function_privilege('anon', 'public.create_order_secure(text,uuid,text,text,text,text,text,text,text,text,text,text,jsonb)', 'execute')
    or has_function_privilege('authenticated', 'public.create_order_secure(text,uuid,text,text,text,text,text,text,text,text,text,text,jsonb)', 'execute')
    or not has_function_privilege('service_role', 'public.create_order_secure(text,uuid,text,text,text,text,text,text,text,text,text,text,jsonb)', 'execute') then
    raise exception 'FAIL: create_order_secure execution grants are not service-role only';
  end if;
  if has_table_privilege('anon', 'public.inventory_stock', 'select')
    or has_table_privilege('authenticated', 'private.order_inventory_reservations', 'select')
    or has_table_privilege('anon', 'public.product_costs', 'select') then
    raise exception 'FAIL: stock internals or private reservations are exposed';
  end if;

  if (select reserved from public.inventory_stock where product_id = 1) <> 1 then
    raise exception 'FAIL: migration did not reserve an existing pending order';
  end if;

  if (select entry_type from public.account_entries where order_return_id =
        '70000000-0000-4000-8000-000000000002') <> 'sales_return'
    or (select category from public.account_entries where order_return_id =
        '70000000-0000-4000-8000-000000000002') <> 'sales_return' then
    raise exception 'FAIL: an existing refund was not reclassified as a sales return';
  end if;
  update public.orders set status = 'cancelled'
  where id = '00000000-0000-4000-8000-000000000002';
  if (select reserved from public.inventory_stock where product_id = 1) <> 0 then
    raise exception 'FAIL: cancelling a pending reserved order did not release stock';
  end if;

  if (select available_quantity from public.get_public_product_availability() where product_id = 3) is not null then
    raise exception 'FAIL: uninitialized inventory must be presented as unknown';
  end if;
  if (select available_quantity from public.get_public_product_availability() where product_id = 2) <> 1 then
    raise exception 'FAIL: public availability returned the wrong sellable count';
  end if;
  perform public.record_inventory_movement(3, 'opening', 0, 0, 'zero-stock test');
  if (select available_quantity from public.get_public_product_availability() where product_id = 3) <> 0 then
    raise exception 'FAIL: initialized zero stock was not reported as unavailable';
  end if;

  begin
    perform public.record_inventory_movement(1, 'opening', 99, null, null);
    raise exception 'FAIL: second opening balance was accepted';
  exception when others then
    if sqlerrm <> 'INVENTORY_ALREADY_INITIALIZED' then raise; end if;
  end;

  perform public.record_inventory_movement(1, 'received', 2, null, 'received');
  perform public.record_inventory_movement(1, 'issued', 1, null, 'issued');
  perform public.record_inventory_movement(1, 'damaged', 1, null, 'damaged');
  perform public.record_inventory_movement(1, 'count', 5, null, 'physical count');
  if (select on_hand from public.inventory_stock where product_id = 1) <> 5 then
    raise exception 'FAIL: received, issued, damaged, or count movement produced a wrong balance';
  end if;

  v_order := public.create_order_secure(
    repeat('a', 64), '20000000-0000-4000-8000-000000000001',
    'Test', 'Buyer', '01012345678', 'القاهرة', 'القاهرة', 'Test address',
    '1', '1', '1', null, '[{"product_id":1,"quantity":2}]'::jsonb
  );
  v_replay := public.create_order_secure(
    repeat('a', 64), '20000000-0000-4000-8000-000000000001',
    'Test', 'Buyer', '01012345678', 'القاهرة', 'القاهرة', 'Test address',
    '1', '1', '1', null, '[{"product_id":1,"quantity":2}]'::jsonb
  );
  v_order_id := (v_order ->> 'order_id')::uuid;
  if v_order_id is null or v_replay ->> 'order_id' <> v_order ->> 'order_id'
    or (v_order ->> 'subtotal')::numeric <> 200
    or (v_order ->> 'shipping')::numeric <> 65
    or (v_order ->> 'total')::numeric <> 265
    or v_order #> '{items,0,unit_cost}' is not null
    or (select (items #>> '{0,unit_cost}')::numeric from public.orders where id = v_order_id) <> 9 then
    raise exception 'FAIL: server pricing or cost snapshot is incorrect';
  end if;
  select count(*) into v_count from public.orders where idempotency_key = '20000000-0000-4000-8000-000000000001';
  if v_count <> 1 then raise exception 'FAIL: idempotent replay created a duplicate order'; end if;

  begin
    perform public.create_order_secure(
      repeat('b', 64), '20000000-0000-4000-8000-000000000002',
      'Test', 'Buyer', '01012345678', 'القاهرة', 'القاهرة', 'Test address',
      '1', '1', '1', null, '[{"product_id":999,"quantity":1}]'::jsonb
    );
    raise exception 'FAIL: unknown product accepted';
  exception when others then
    if sqlerrm <> 'ORDER_INVALID_ITEMS' then raise; end if;
  end;
  begin
    perform public.create_order_secure(
      repeat('b', 64), '20000000-0000-4000-8000-000000000003',
      'Test', 'Buyer', '01012345678', 'القاهرة', 'القاهرة', 'Test address',
      '1', '1', '1', null, '[{"product_id":1,"quantity":1},{"product_id":1,"quantity":1}]'::jsonb
    );
    raise exception 'FAIL: duplicate product lines accepted';
  exception when others then
    if sqlerrm <> 'ORDER_INVALID_ITEMS' then raise; end if;
  end;

  update public.orders set status = 'confirmed' where id = v_order_id;
  if (select reserved from public.inventory_stock where product_id = 1) <> 2 then
    raise exception 'FAIL: confirming order did not reserve stock';
  end if;
  begin
    perform public.record_inventory_movement(1, 'issued', 4, null, null);
    raise exception 'FAIL: stock movement issued reserved units';
  exception when others then
    if sqlerrm <> 'INVENTORY_INSUFFICIENT_AVAILABLE' then raise; end if;
  end;
  update public.orders set status = 'processing' where id = v_order_id;
  update public.orders set status = 'cancelled' where id = v_order_id;
  if (select reserved from public.inventory_stock where product_id = 1) <> 0
    or (select on_hand from public.inventory_stock where product_id = 1) <> 5 then
    raise exception 'FAIL: cancelling order did not release reservation without consuming stock';
  end if;

  update public.orders set status = 'confirmed' where id = v_order_id;
  update public.orders set status = 'shipped' where id = v_order_id;
  if (select on_hand from public.inventory_stock where product_id = 1) <> 3
    or (select reserved from public.inventory_stock where product_id = 1) <> 0 then
    raise exception 'FAIL: shipping did not consume reserved units exactly once';
  end if;
  update public.orders set status = 'delivered' where id = v_order_id;
  update public.orders set status = 'delivered' where id = v_order_id;
  select count(*) into v_count from public.account_entries
  where order_id = v_order_id and entry_type = 'income' and category = 'delivered_order';
  if v_count <> 1 then raise exception 'FAIL: delivered income was missing or duplicated'; end if;
  if (select amount from public.account_entries where order_id = v_order_id and category = 'delivered_order') <> 200 then
    raise exception 'FAIL: delivered income includes shipping or has wrong subtotal';
  end if;

  v_return_id := public.record_order_return(
    '60000000-0000-4000-8000-000000000001', v_order_id,
    '[{"product_id":1,"quantity":1,"disposition":"restock"}]'::jsonb,
    'cash', 'partial saleable return'
  );
  v_return_replay := public.record_order_return(
    '60000000-0000-4000-8000-000000000001', v_order_id,
    '[{"product_id":1,"quantity":1,"disposition":"restock"}]'::jsonb,
    'cash', 'partial saleable return'
  );
  if v_return_id is null or v_return_replay <> v_return_id
    or (select on_hand from public.inventory_stock where product_id = 1) <> 4
    or (select count(*) from public.account_entries where order_return_id = v_return_id) <> 1 then
    raise exception 'FAIL: saleable partial return or idempotent return replay failed';
  end if;
  begin
    perform public.record_order_return(
      '60000000-0000-4000-8000-000000000001', v_order_id,
      '[{"product_id":1,"quantity":2,"disposition":"restock"}]'::jsonb,
      'cash', 'changed payload'
    );
    raise exception 'FAIL: conflicting return idempotency key was accepted';
  exception when others then
    if sqlerrm <> 'ORDER_RETURN_IDEMPOTENCY_CONFLICT' then raise; end if;
  end;

  perform public.record_order_return(
    '60000000-0000-4000-8000-000000000002', v_order_id,
    '[{"product_id":1,"quantity":1,"disposition":"damaged"}]'::jsonb,
    'other', 'remaining damaged item'
  );
  if (select on_hand from public.inventory_stock where product_id = 1) <> 4
    or (select sum(amount) from public.account_entries where order_id = v_order_id and category = 'sales_return') <> 200
    or (select sum(quantity) from public.order_return_items where order_id = v_order_id) <> 2
    or (select count(*) from public.inventory_movements where order_id = v_order_id and movement_type = 'return_damaged') <> 1 then
    raise exception 'FAIL: damaged return changed saleable stock or refund did not include both product units';
  end if;
  if (select sales_returns_total from public.get_account_month_summary(
      date_trunc('month', (now() at time zone 'Africa/Cairo')::date)::date)) <> 300
    or (select expense_total from public.get_account_month_summary(
      date_trunc('month', (now() at time zone 'Africa/Cairo')::date)::date)) <> 0 then
    raise exception 'FAIL: returns were counted as expenses or omitted from the monthly sales-return summary';
  end if;
  if (select gross_profit from public.get_product_profit_summary() where product_id = 1) <> -18
    or not (select estimated_cost from public.get_product_profit_summary() where product_id = 1)
    or (select unit_profit from public.get_product_profit_summary() where product_id = 1) <> 91 then
    raise exception 'FAIL: product profit did not use historical cost snapshots and return dispositions';
  end if;

  begin
    perform public.record_order_return(
      '60000000-0000-4000-8000-000000000003', v_order_id,
      '[{"product_id":1,"quantity":1,"disposition":"restock"}]'::jsonb,
      'other', null
    );
    raise exception 'FAIL: return quantity exceeded the ordered quantity';
  exception when others then
    if sqlerrm <> 'ORDER_RETURN_QUANTITY_EXCEEDED' then raise; end if;
  end;
  begin
    perform public.record_inventory_movement(1, 'returned', 1, null, 'unlinked return');
    raise exception 'FAIL: unlinked stock return was accepted';
  exception when others then
    if sqlerrm <> 'INVENTORY_INVALID_MOVEMENT' then raise; end if;
  end;

  begin
    update public.orders set status = 'cancelled' where id = v_order_id;
    raise exception 'FAIL: fulfilled order was reopened';
  exception when others then
    if sqlerrm not in ('ORDER_STATUS_TRANSITION_INVALID', 'ORDER_FULFILLED_CANNOT_REOPEN') then raise; end if;
  end;
  if (select status from public.orders where id = v_order_id) <> 'delivered' then
    raise exception 'FAIL: recording a return incorrectly reopened or cancelled the delivered order';
  end if;

end $$;

-- Non-admin sessions see no admin data and cannot edit catalog/account records.
begin;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"30000000-0000-4000-8000-000000000001","app_metadata":{"role":"user"}}', true);
do $$
declare affected integer;
begin
  if (select count(*) from public.orders) <> 0 or (select count(*) from public.account_entries) <> 0 then
    raise exception 'FAIL: non-admin authenticated user can read private order/account data';
  end if;
  if (select count(*) from public.product_costs) <> 0
    or (select count(*) from public.get_product_profit_summary()) <> 0 then
    raise exception 'FAIL: non-admin authenticated user can read product costs or profit reports';
  end if;
  update public.products set price = 1 where id = 1;
  get diagnostics affected = row_count;
  if affected <> 0 then raise exception 'FAIL: non-admin user edited a product'; end if;
end $$;
rollback;

begin;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"30000000-0000-4000-8000-000000000001","app_metadata":{"role":"user"}}', true);
do $$
begin
  begin
    insert into public.account_entries (entry_type, category, amount, payment_method)
    values ('income', 'other_income', 1, 'other');
    raise exception 'FAIL: non-admin account entry insert was accepted';
  exception when insufficient_privilege then null;
  end;
  begin
    perform public.record_inventory_movement(1, 'received', 1, null, null);
    raise exception 'FAIL: non-admin inventory movement was accepted';
  exception when others then
    if sqlerrm <> 'INVENTORY_NOT_AUTHORIZED' then raise; end if;
  end;
  begin
    perform public.record_order_return(
      '70000000-0000-4000-8000-000000000001',
      '00000000-0000-4000-8000-000000000001',
      '[{"product_id":1,"quantity":1,"disposition":"restock"}]'::jsonb,
      'other', null
    );
    raise exception 'FAIL: non-admin return was accepted';
  exception when others then
    if sqlerrm <> 'ORDER_RETURN_NOT_AUTHORIZED' then raise; end if;
  end;
end $$;
rollback;

begin;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"10000000-0000-4000-8000-000000000001","app_metadata":{"role":"admin"}}', true);
do $$
declare affected integer;
begin
  update public.products set price = 101 where id = 1;
  get diagnostics affected = row_count;
  if affected <> 1 then raise exception 'FAIL: admin product edit was blocked'; end if;
  insert into public.account_entries (entry_type, category, amount, payment_method)
  values ('income', 'other_income', 1, 'other');
  perform public.record_inventory_movement(1, 'received', 1, null, 'admin permission test');
end $$;
rollback;

-- Reapplying the delivered-order migration must not duplicate backfilled income.
\ir ../database/delivered-orders-accounting-migration.sql
do $$
begin
  if (select count(*) from public.account_entries
      where order_id = '00000000-0000-4000-8000-000000000001' and category = 'delivered_order') <> 1 then
    raise exception 'FAIL: re-running delivered-order migration duplicated historical income';
  end if;
end $$;

-- Deliberately leave two independent stock-one purchases pending for the
-- runner's concurrent two-session race test.
select 'database setup and sequential assertions passed' as test_result;
