-- 2) Product catalog table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null,
  old_price numeric,
  tag text,
  meta text,
  rating numeric default 4.8,
  specs jsonb default '{}',
  image text,
  type text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Create admin accounts with Supabase Auth. Assign app_metadata.role = 'admin'
-- using a trusted server or the Supabase Dashboard, never from browser code.

-- Seed default products for the storefront
insert into public.products (id, name, category, price, old_price, tag, meta, rating, specs, image, type)
values
  (1, 'لوح كيك ذهبي دائري 20 سم', 'boards', 45, 55, 'الأكثر مبيعاً', 'ذهبي · 20 سم · 3 مم', 4.9, '{"diameter":"20 سم","thickness":"3 مم","shape":"دائري","color":"ذهبي","quantity":"1 قطعة"}', null, 'goldboard'),
  (2, 'علبة كيك بيضاء 20×20×20', 'boxes', 85, null, 'جديد', 'كرتون غذائي · 20 سم', 4.8, '{"width":"20 سم","length":"20 سم","height":"20 سم","material":"كرتون غذائي","color":"أبيض","quantity":"1 قطعة"}', null, 'box'),
  (3, 'لوح كيك فضي دائري 25 سم', 'boards', 55, null, '', 'فضي · 25 سم · 3 مم', 4.7, '{"diameter":"25 سم","thickness":"3 مم","shape":"دائري","color":"فضي","quantity":"1 قطعة"}', null, 'silverboard'),
  (4, 'علبة كب كيك — 6 قطع', 'cupcakes', 62, 75, 'عرض', '6 قطع · نافذة شفافة', 4.9, '{"pieces":"6 قطع","material":"كرتون","window":"شفاف","color":"أبيض","quantity":"1 علبة"}', null, 'cup'),
  (5, 'علبة كيك بيضاء 25×25×25', 'boxes', 105, null, '', 'كرتون غذائي · 25 سم', 4.8, '{"width":"25 سم","length":"25 سم","height":"25 سم","material":"كرتون غذائي","color":"أبيض","quantity":"1 قطعة"}', null, 'box'),
  (6, 'شريط ساتان أزرق — 10 متر', 'packaging', 38, null, 'جديد', 'أزرق ملكي · 10 متر', 4.6, '{"length":"10 متر","material":"ساتان","color":"أزرق","quantity":"1 لفافة"}', null, 'ribbon'),
  (7, 'علبة كب كيك — 12 قطعة', 'cupcakes', 88, null, '', '12 قطعة · نافذة شفافة', 4.8, '{"pieces":"12 قطعة","material":"كرتون","window":"شفاف","color":"أبيض","quantity":"1 علبة"}', null, 'cup'),
  (8, 'لوح كيك ذهبي دائري 30 سم', 'boards', 75, null, '', 'ذهبي · 30 سم · 3 مم', 4.9, '{"diameter":"30 سم","thickness":"3 مم","shape":"دائري","color":"ذهبي","quantity":"1 قطعة"}', null, 'goldboard'),
  (9, 'علبة كيك طويلة 30 سم', 'boxes', 130, null, 'جديد', 'طويلة · 30×30×20 سم', 4.7, '{"width":"30 سم","length":"30 سم","height":"20 سم","material":"كرتون غذائي","color":"أبيض","quantity":"1 قطعة"}', null, 'box'),
  (10, 'مجموعة ملصقات سُكّر', 'packaging', 25, null, '', '36 ملصقاً · دائري', 4.6, '{"quantity":"36 ملصقاً","type":"ملصقات","color":"متعدد","material":"ورق"}', null, 'ribbon')
on conflict (id) do nothing;

do $$
declare
  product_id_sequence text := pg_get_serial_sequence('public.products', 'id');
begin
  if product_id_sequence is not null then
    execute format(
      'select setval(%L, coalesce(max(id), 1), max(id) is not null) from public.products',
      product_id_sequence
    );
    execute format('revoke all on sequence %s from public, anon', product_id_sequence);
    execute format('grant usage, select on sequence %s to authenticated', product_id_sequence);
  end if;
end $$;

-- Disable access to any legacy plaintext credential table without deleting data.
-- Remove and rotate legacy credentials separately after confirming admin migration.
do $$
declare
  policy_name text;
begin
  if to_regclass('public.admin_credentials') is not null then
    execute 'alter table public.admin_credentials enable row level security';
    for policy_name in
      select policyname
      from pg_policies
      where schemaname = 'public' and tablename = 'admin_credentials'
    loop
      execute format('drop policy %I on public.admin_credentials', policy_name);
    end loop;
    execute 'revoke all on public.admin_credentials from public, anon, authenticated';
  end if;
end $$;

alter table public.products enable row level security;

do $$
declare
  policy_name text;
begin
  for policy_name in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'products'
  loop
    execute format('drop policy %I on public.products', policy_name);
  end loop;
end $$;

create policy "products_public_select"
on public.products
for select
to anon, authenticated
using (true);

revoke insert, update, delete on public.products from public, anon;
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;

create policy "products_admin_insert"
on public.products
for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "products_admin_update"
on public.products
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "products_admin_delete"
on public.products
for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- optional: view for product specs (for admin dashboard)
create or replace view public.product_specs_view
with (security_invoker = true) as
select p.id, p.name, p.category, p.price, p.old_price, p.tag, p.meta, p.rating, p.specs, p.image
from public.products p;
