-- 1) Admin credentials table
create table if not exists public.admin_credentials (
  username text primary key,
  password text not null,
  full_name text,
  created_at timestamptz default now()
);

-- Example demo admin user
insert into public.admin_credentials (username, password, full_name)
values ('admin', 'zmzm123', 'Zamzam Admin')
on conflict (username) do nothing;

-- 2) Product catalog table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null,
  old_price numeric,
  tag text,
  meta text,
  rating numeric default 4.8,
  specs jsonb default '{}',
  type text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- optional: enable row level security (RLS) if you want stricter access
-- alter table public.products enable row level security;
-- alter table public.admin_credentials enable row level security;

-- optional: view for product specs (for admin dashboard)
create or replace view public.product_specs_view as
select p.id, p.name, p.category, p.price, p.old_price, p.tag, p.meta, p.rating, p.specs
from public.products p;
